export {default as LoginPage} from './LoginPage'
export {default as HomePage} from './HomePage'
export {default as MessagePage} from './MessagePage'
export {default as UserPage} from './UserPage'
export {default as ConstructionPage} from './ConstructionPage'
